// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBy2SwBVbgTUh94cJxmbP4jVbJ9w9CGs0',
    appId: '1:273862348012:web:cd57dc3fb0fa8656c3e9c9',
    messagingSenderId: '273862348012',
    projectId: 'tast3-c07df',
    authDomain: 'tast3-c07df.firebaseapp.com',
    storageBucket: 'tast3-c07df.firebasestorage.app',
    measurementId: 'G-ZYQ2EWVCYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhbts5kLJzVk1t1anB9FaG8TjERl7538A',
    appId: '1:273862348012:android:91bd45f01d3d7e92c3e9c9',
    messagingSenderId: '273862348012',
    projectId: 'tast3-c07df',
    storageBucket: 'tast3-c07df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTnLpXY-e0LZGUsUWOglka8Qux9jNoifE',
    appId: '1:273862348012:ios:41be1f4c8add06a9c3e9c9',
    messagingSenderId: '273862348012',
    projectId: 'tast3-c07df',
    storageBucket: 'tast3-c07df.firebasestorage.app',
    iosBundleId: 'com.example.task3',
  );
}
